dist: trusty
sudo: false
language: php
php:
- '7.1.14'
services:
- mysql
install:
- mysql -e 'CREATE DATABASE aurora;'
- git clone ${PRODUCT_REPOSITORY_URL} ./product
- php ./add.php
- composer install -d ./product
- npm install -g newman
script:
- php ./product/travis.php
- chmod +x ./product/travis.sh
- ./product/travis.sh -t build
after_success: 
- ./product/travis.sh -t upload
env:
  global:
  - PRODUCT_NAME=webmail-pro-bitnami
  - PRODUCT_REPOSITORY_URL=https://github.com/afterlogic/webmail-pro-8
