dist: trusty
sudo: false
language: php
php:
- '7.1.14'
services:
- mysql
install:
- mysql -e 'CREATE DATABASE aurora;'
- git clone ${PRODUCT_REPOSITORY_URL} ./product
- php ./add.php
- cd ./product | composer install
- npm install -g newman
script:
- cd ./product | php ./travis.php
- cd ./product | chmod +x ./travis.sh
- cd ./product | ./travis.sh -t build
after_success: 
- cd ./product | ./travis.sh -t upload
env:
  global:
  - PRODUCT_NAME=webmail-pro-bitnami
